[general]
width = 610
height = 800
custom_texture = false
trail_speed = 700
trail_width = 50
trail_offset = -1 # 1 = starts at top, 0 = starts in the middle, -1 = starts at the bottom

[colors]
green_fret = "#00e430"
red_fret = "#e62937"
yellow_fret = "#fdf900"
blue_fret = "#0079f1"
orange_fret = "#ffa100"
strum_up_color = "#873cbe"
strum_down_color = "#873cbe"

# For bindings, please check https://hardwaretester.com/gamepad to put in your bindings!
[bindings]
controller_id = 0
dpad_axis = true # This setting should only be false if you are on a raphnet, or another HID joystick adapter
green_binding = 0
red_binding = 1
yellow_binding = 4
blue_binding = 3
orange_binding = 6
strum_up_binding = 12
strum_down_binding = 13